### ISSUE TITLE
how to use this code?

### ISSUE THREAD

**Issue by r-baradaran** [bloomsburyai/question-generation#1]
Hello,
how to use this code and create a QG model?

**Comment by tomhosking** [comment]
This implementation is still a work in progress, and is not yet able to train a QG model out of the box.

**Comment by shizhediao** [comment]
> This implementation is still a work in progress, and is not yet able to train a QG model out of the box.

is it finished now?

**Comment by pidugusundeep** [comment]
@shizhediao yeah it works now
