### ISSUE TITLE
Difference between MALUUBA and MALUUBA_RL

### ISSUE THREAD

**Issue by rpoli40** [bloomsburyai/question-generation#10]
Hi, I'm using commit be13417 and paid attention you made some changes later on. So what is the difference between MALUUBA and RL. Is it just a naming?

**Comment by tomhosking** [comment]
The difference is that the *_RL model (now RL-* models) include the placeholders and losses for policy gradient training. The difference between SEQ2SEQ and MALUUBA model types is the additional layer of condition encoding, which I replaced with the `advanced_condition_encoding ` flag. If you want to fine tune the model then you need to use an RL model type (even for the first part of the training). Hope that helps.

**Comment by rpoli40** [comment]
Once the latest commit is used when the training starts it prints that the model type is RL-S2S. Is it correct and then I'm using the approach described in the paper ("Machine comprehension by text-to-text neural question generation")

**Comment by tomhosking** [comment]
To replicate the approach used in the paper, run `./train.sh --advanced_condition_encoding --nocontext_as_set`. You could also add the flag `--model_type RL-MALUUBA` if you wanted to give the run a more readable name, but this is optional.

**Comment by rpoli40** [comment]
Thank you very much. Can you also list flags that should be used with other
types of approaches you have.

**Comment by tomhosking** [comment]
Check `flags.py` for a full list

**Comment by rpoli40** [comment]
Hi Tom,
Would you recommend retraining MPCM.py and language model if I would like
to supplement Squad dataset with my own data. In case you recommend to
retrain those are there any flags/arguments I should use?
Thank you
