### ISSUE TITLE
is this repo finished now?

### ISSUE THREAD

**Issue by shizhediao** [bloomsburyai/question-generation#12]
Thanks for your contribution.
I was wondering if this repo finished and how to use my corpus to train this model? thanks

**Comment by tomhosking** [comment]
You can now train a model using this repo. Put your corpus in the same format as the squad files in `./data/train-v1.1,json` and `./data/dev-v1.1.json`, then run `train.sh --num_dev_samples ???` where ??? is the size of your dev split. Check `./src/flags.py` for more configuration options.

**Comment by shizhediao** [comment]
> You can now train a model using this repo. Put your corpus in the same format as the squad files in `./data/train-v1.1,json` and `./data/dev-v1.1.json`, then run `train.sh --num_dev_samples ???` where ??? is the size of your dev split. Check `./src/flags.py` for more configuration options.

thanks so much!
