### ISSUE TITLE
Could you help me upload these missing files which are needed in evaluation.

### ISSUE THREAD

**Issue by shizhediao** [bloomsburyai/question-generation#14]
Looks like that repo is missing some files (this folder models/saved...doesn't exist):
File "/home/ec2-user/SageMaker/question-generation-be134175652204f3bf51cb194454d7b72c8b8105/src/langmodel/lm.py", line 101,in load_from_chkpt
with open(path+'/vocab.json') as f:
**FileNotFoundError: [Errno 2] No such file or directory: '../models/saved/lmtest/vocab.json'**
Exception ignored in: <bound method LstmLmInstance.**del** of <langmodel.lm.LstmLmInstance object at 0x7f9d8b8cb550>>
Traceback (most recent call last):
File "/home/ec2-user/SageMaker/question-generation-be134175652204f3bf51cb194454d7b72c8b8105/src/langmodel/lm.py", line 98, in **del**
self.sess.close()
AttributeError: 'LstmLmInstance' object has no attribute 'sess'
Exception ignored in: <bound method QANetInstance.**del** of <qa.qanet.instance.QANetInstance object at 0x7f9d8b8cb518>>
Traceback (most recent call last):
File "/home/ec2-user/SageMaker/question-generation-be134175652204f3bf51cb194454d7b72c8b8105/src/qa/qanet/instance.py", line53, in **del**
self.sess.close()
AttributeError: 'QANetInstance' object has no attribute 'sess'

could you help me upload these missing files which are needed in evaluation.

**Comment by tomhosking** [comment]
You can disable the QA/LM evaluation by setting the flag `--noeval_metrics` - it will still calculate the F1 and BLEU scores. The extra model files are then not required.

**Comment by tomhosking** [comment]
I've just committed an update to `setup.sh` that will download the QA and LM models. You may need to move them around to get them to work with `eval.py`.

**Comment by shizhediao** [comment]
> I've just committed an update to `setup.sh` that will download the QA and LM models. You may need to move them around to get them to work with `eval.py`.

got it, Thanks!

**Comment by shivaat** [comment]
I noticed that non of the files shared via dropbox, listed in setup.sh are available anymore.
Even when I set the flag `--noeval_metrics`, running `demo.sh` gives me the error for missing `vocab.json`.

> You can disable the QA/LM evaluation by setting the flag `--noeval_metrics` - it will still calculate the F1 and BLEU scores. The extra model files are then not required.

**Comment by tomhosking** [comment]
Sorry, I'm moving some of my stuff around and it took the models with it. While `--noeval_metrics` does stop you requiring the QA and LM model files, the demo will always need a trained model to allow you to run inference. I'll try and get the pre-trained models back up soon.

**Comment by tomhosking** [comment]
Check the latest commit for updated URLs.
