### ISSUE TITLE
Unable to save the model

### ISSUE THREAD

**Issue by ayush2051** [bloomsburyai/question-generation#16]
@tomhosking I am unable to save the checkpoints while training the model. I guess m unable to figure out what should be in the restore path. Can u help me in this regard?

**Comment by tomhosking** [comment]
Checkpoints are saved to the location specified by the `--model_dir` flag, default is `./models`. You may need to create this directory?

**Comment by ayush2051** [comment]
@tomhosking thanks a lot for the reply. Got it fixed.

> Checkpoints are saved to the location specified by the `--model_dir` flag, default is `./models`. You may need to create this directory?
