### ISSUE TITLE
The flag 'log_dir' is defined twice - While running the ./demo.sh

### ISSUE THREAD

**Issue by pidugusundeep** [bloomsburyai/question-generation#18]
Error : 

> absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from flags.  Description from first occurrence: directory to write logfiles into

What's the fix to this?

**Comment by tomhosking** [comment]
Could you please run the following command and post the output here?
`pip freeze | grep absl`

**Comment by pidugusundeep** [comment]
```cmd
$ pip freeze | grep absl

   absl-py==0.5.0
```

**Comment by tomhosking** [comment]
Weird, I haven't seen this before. I guess you can comment out the declaration in flags.py for now, I'll see if I can find out why it works for me.

**Comment by pidugusundeep** [comment]
![Screenshot from 2019-07-10 10-29-33](https://user-images.githubusercontent.com/10946649/60958932-e9e8a980-a324-11e9-950c-81dd32229918.png)
had this issue while installing the requirements is there a problem with the installation?

**Comment by tomhosking** [comment]
`requirements.txt` specifies tensorflow version 1.12, I don't know if 1.14 is compatible with the code.

**Comment by pidugusundeep** [comment]
Sorry i was using ```python 3.7``` and i was unable to install ```tensorflow 1.12.0``` so i downgraded to ```python 3.6``` and i was able to run the application **(./demo.sh)** .
