### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by KJ-Lin** [bloomsburyai/question-generation#2]
hello， The code has problem when it run，the issue is “tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -22”
which at the code “ alignments_padded = tf.pad(alignments, [[0, 0], [0, self.units-tf.shape(alignments)[-1]]], 'CONSTANT')”

cloud you help to solve it   thanks！

**Comment by tomhosking** [comment]
This should have been fixed in https://github.com/bloogram/question-generation/commit/7e52187ea9a4b0f23d11c9f8d4641d6914008b09
