### ISSUE TITLE
How do i configure it to get multiple questions instead of just the first occurance of the answer ?

### ISSUE THREAD

**Issue by pidugusundeep** [bloomsburyai/question-generation#20]

**Comment by tomhosking** [comment]
This isn't currently a supported option. The model takes as input the span of the answer, so if the answer exists in multiple locations you could modify the demo code to find all of them and request questions based on each of these locations.

**Comment by pidugusundeep** [comment]
@tomhosking I was able to modify the code and get multiple questions for a given answer. Thanks.

**Comment by abbyDC** [comment]
> @tomhosking I was able to modify the code and get multiple questions for a given answer. Thanks.

Hi! Will it be possible for you to share this modification? It would also help me in my research. Thank you!

**Comment by pidugusundeep** [comment]
@abbyDC https://github.com/pidugusundeep/question-generation-2/commits/master check this out I hope this helps.

**Comment by abbyDC** [comment]
> @abbyDC https://github.com/pidugusundeep/question-generation-2/commits/master check this out I hope this helps.

Appreciate this. Will check this out. Thank you for your help!
