### ISSUE TITLE
Unable to use tensorflow_hub

### ISSUE THREAD

**Issue by pidugusundeep** [bloomsburyai/question-generation#21]
Iam planning to use universal sentence encoder in the app.py and when i try to import ```tensorflow_hub``` it always throws this error  
```python
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from flags.  Description from first occurrence: directory to write logfiles into
```

How do I fix this?

**Comment by tomhosking** [comment]
Hi, as before you're probably using a newer version of TF than is supported by this repo. I haven't tested with TF>1.12. Please do submit a PR if you get it working with v2.0!

**Comment by pidugusundeep** [comment]
@tomhosking  thanks for the quick response, I am using TensorFlow 1.12.0 only for running the application, it running file but if I wanted to add the tensorflow_hub I have difficulty with the above error mentioned with a flag.

**Comment by tomhosking** [comment]
Ah I assumed `tensorflow-hub` required a recent version of TF but [looks like it only needs >=1.7.0](https://www.tensorflow.org/hub/installation).

It may be easiest to modify `flags.py` and change the `log_dir` flag to use a different (non-colliding) name, as well as the references to this flag in the code. Again feel free to submit a PR with this change as it seems it will make it more compatible with recent versions of TF.

**Comment by pidugusundeep** [comment]
@tomhosking Got it thanks will give an update soon on this.
