### ISSUE TITLE
Replicate the RL paper parameters and to run 

### ISSUE THREAD

**Issue by ayush2051** [bloomsburyai/question-generation#25]
@rpoli40 Were u able to run it and replicate as given in the RL paper. I tried it but ran into an error 
ValueError: Dimensions must be equal, but are 2269 and 2446 for 'train_loss/mul_4' (op: 'Mul') with input shapes: [?,?,2269], [?,?,2446].

I kept the advanced encoding & context_as_set FLAG as TRUE. Am I doing it right or do I need to change any other parameters in the flags file.

**Comment by tomhosking** [comment]
Hi, could you please confirm exactly what command you ran to trigger this error?

**Comment by ayush2051** [comment]
Yeahh Tom I ran the script as ./train.sh --advanced_condition_encoding --nocontext_as_set --model_type RL-MALUUBA with all the flags as set earlier to defaults. Am I doing it right or do I need to change any other flags?

**Comment by tomhosking** [comment]
@ayush2051 I just tried running with those flags and it worked OK for me. Did you find the problem?

**Comment by ayush2051** [comment]
@tomhosking thanks a lot. Sorry couldn't reply, it worked finally.
