### ISSUE TITLE
Do you have a graph_def file for the models ?

### ISSUE THREAD

**Issue by pidugusundeep** [bloomsburyai/question-generation#27]
I am trying out [https://github.com/IntelAI/tools/tree/master/tensorflow_quantization#steps-for-fp32-optimized-frozen-graph](https://github.com/IntelAI/tools/tree/master/tensorflow_quantization#steps-for-fp32-optimized-frozen-graph)  and I would like to know if you have any `.pb` or `.pbtxt` files along with the checkpoint files which you provided in the `./models`

**Comment by tomhosking** [comment]
I don't have them, but you have the code that builds the graph so you should be able to write the graph to disk.

**Comment by pidugusundeep** [comment]
@tomhosking may I know where exactly it is?

**Comment by tomhosking** [comment]
The model is built [here](https://github.com/bloomsburyai/question-generation/blob/master/src/demo/instance.py#L19), and you can then access the graph with `self.model.graph`, eg 
```
tf.train.write_graph(self.model.graph, path_to_model_pb,
                     'saved_model.pb', as_text=False)
```
(see [this stackoverflow post](https://stackoverflow.com/questions/45994346/tensorflow-saving-a-model-to-model-pb-to-visualize-it-later))

**Comment by pidugusundeep** [comment]
@tomhosking Thanks it's working!
