### ISSUE TITLE
What is the model trained on ?

### ISSUE THREAD

**Issue by pidugusundeep** [bloomsburyai/question-generation#29]
Is it with Squad1.1 or 2.0?

**Comment by tomhosking** [comment]
The questions added in squad 2 are adversarial and don't have answers, so can't be used to train the model

**Comment by pidugusundeep** [comment]
Which data is more appropriate for training is it squad 1.1 or 2.0 as I see your code having the flexibility to do this and I tweaked these lines and i was able to start training 
https://github.com/bloomsburyai/question-generation/blob/af189b1e43b5fca3f6a6f5d7e40362a4235c73fb/src/helpers/loader.py#L46-L49
But not sure whether that would help or get worse? please suggest .

Changes:
1. Basically neglecting the last parameter(5th one) 
2. adding `if not qa['is_impossible']:` and commenting the else.

**Comment by tomhosking** [comment]
> The questions added in squad 2 are adversarial and don't have answers, so can't be used to train the model

**Comment by pidugusundeep** [comment]
Got it thanks.
