### ISSUE TITLE
How do i get the .ckpt file for the model ?

### ISSUE THREAD

**Issue by pidugusundeep** [bloomsburyai/question-generation#30]
How do I get the .ckpt file for the model? Or generate?

**Comment by tomhosking** [comment]
It's in the zip file provided, it's just got a different name. It's saved [here](https://github.com/bloomsburyai/question-generation/blob/master/src/train.py#L472).

**Comment by pidugusundeep** [comment]
![Screenshot from 2019-08-23 13-21-09](https://user-images.githubusercontent.com/10946649/63582230-56a6c300-c5b6-11e9-9af2-b876b72dae50.png)
Is that the second file listed in the structure? can I rename the same and use it ??

**Comment by tomhosking** [comment]
You should just be able to do something like `saver.restore(sess, restore_path + 'model.checkpoint')` (or actually I think `saver.restore(sess, restore_path)` works and uses the latest file listed in `checkpoint`)

**Comment by pidugusundeep** [comment]
Got it thanks.
