### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by ayush2051** [bloomsburyai/question-generation#42]
Hi, I am getting a list out of index error

qs.extend(self.get_q_batches(ctxts[start_ix:end_ix], ans[start_ix:end_ix], ans_pos[start_ix:end_ix]))
ctxt_feats[0] = np.array(ctxt_feats[0], dtype=bytes)

Could you please help me regarding the same?

**Comment by tomhosking** [comment]
I'd guess that your context, answer and answer position arrays are not the same length
