### ISSUE TITLE
Not installing in the requirements.txt

### ISSUE THREAD

**Issue by tanik4u** [bloomsburyai/question-generation#7]
"en-core-web-sm==2.0.0" contained in requirements.txt file is not installing. I want to run this code to generate question given context and answer for my dataset, please help. It's urgent. 

Please give me a proper documentation.

**Comment by tomhosking** [comment]
You can remove that line from `requirements.txt` - it will be installed by `setup.sh` but for some reason is included in the output of `pip freeze`.

Then, run the demo with `PYTHONPATH=$PYTHONPATH:./src/ python ./src/demo/app.py --data_path ./data/ $@`

**Comment by TanikSaikh** [comment]
ok, thanks. 
Finally, when I am running the command "./demo.sh --model_type MALUUBA --context_as_set --glove_vocab", it's giving error like below:
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Please help...

**Comment by tomhosking** [comment]
You can ignore that message.

**Comment by tanik4u** [comment]
Ok... 
When I am running the command "sh train.sh", it gives sh train.sh like below:
Illegal instruction (core dumped)
please help!!

**Comment by tomhosking** [comment]
That sounds like an error with TensorFlow, not this code

**Comment by tanik4u** [comment]
Now after resolving all the previous issues when I am running "./demo.sh --model_type MALUUBA --context_as_set --glove_vocab" command it's is giving the error like below: 
"ModuleNotFoundError: No module named 'seq2seq_model'" at line 8 in instance.py
Is the seq2seq model is not incorporated.
please help!!

**Comment by tomhosking** [comment]
Run the demo using the command in my first comment instead.

**Comment by tanik4u** [comment]
![screenshot from 2018-11-20 20-20-33](https://user-images.githubusercontent.com/35554114/48781377-e8209600-ed01-11e8-9062-cf5338922514.png)
Now I am getting the error as shown in the screen shot after running the demo
please help!!

**Comment by tomhosking** [comment]
Make sure you checked out the commit referenced in the readme

**Comment by TanikSaikh** [comment]
In the starting, there is a line "To use the saved models, checkout commit be134175652204f3bf51cb194454d7b72c8b8105 - breaking changes have been made since then, I will update the models once retrained." 
But I Can't understand!! What shall I have to do? 
Please tell me how to do that.

**Comment by tomhosking** [comment]
Run `git checkout commit be134175652204f3bf51cb194454d7b72c8b8105` to use the version compatible with the pre-trained models.

Please note that this is research code, it may not be suitable for your requirements and may require some modification to work in your environment. If you're not familiar with `git` or TensorFlow it may not be suitable for you.
