### ISSUE TITLE
Unrecognised model type: MALUUBA

### ISSUE THREAD

**Issue by SeekPoint** [bloomsburyai/question-generation#8]
(.venv) gpuws@gpuws32g:~/ub16_prj/question-generation$ bash train.sh 
WARNING:tensorflow:From /home/gpuws/ub16_prj/question-generation/.venv/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Run ID is  1544494702
Model type is  MALUUBA
Loaded SQuAD with  75722  triples
Unrecognised model type: MALUUBA
(.venv) gpuws@gpuws32g:~/ub16_prj/question-generation$

**Comment by tomhosking** [comment]
Please checkout commit 9d2aec68374549cdab9b20b9f6f9d83804096d17 for now, I'm in the process of changing a few things.

**Comment by tomhosking** [comment]
The latest commit should work correctly with the updated `setup.sh`
